---
abstract: 'Twitter when you release with Dist::Zilla'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101151'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Twitter
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Dist::Zilla::Plugin::Twitter:
    file: lib/Dist/Zilla/Plugin/Twitter.pm
    version: 0.003
recommends: {}
requires: {}
resources:
  repository: http://github.com/dagolden/dist-zilla-plugin-twitter
version: 0.003
