---
abstract: 'Twitter when you release with Dist::Zilla'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dist::Zilla::App::Tester: 0
  Dist::Zilla::Role::Releaser: 0
  Dist::Zilla::Tester: 0
  File::Find: 0
  File::Temp: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  Params::Util: 0
  Path::Class: 0
  Sub::Exporter: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Twitter
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Dist::Zilla::Plugin::Twitter:
    file: lib/Dist/Zilla/Plugin/Twitter.pm
    version: 0.007
recommends: {}
requires:
  Carp: 0
  Dist::Zilla: 2.101170
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::TextTemplate: 0
  Math::BigFloat: 0
  Moose: 0.99
  Net::Netrc: 0
  Net::Twitter: 3
  WWW::Shorten::TinyURL: 1
  namespace::autoclean: 0.09
  perl: 5.008
  utf8: 0
resources:
  repository: http://github.com/dagolden/dist-zilla-plugin-twitter
version: 0.007
