---
abstract: 'Twitter when you release with Dist::Zilla'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  Dist::Zilla::App::Tester: 0
  Dist::Zilla::Role::Releaser: 0
  Dist::Zilla::Tester: 0
  File::Find: 0
  File::Temp: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  Module::Build: 0.3601
  Params::Util: 0
  Sub::Exporter: 0
  Test::More: 0.88
  base: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Twitter
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Config::INI::Reader: 0
  Config::INI::Writer: 0
  Dist::Zilla: 4
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::TextTemplate: 0
  Dist::Zilla::Util: 0
  File::Path: 0
  File::Spec: 0
  Moose: 0.99
  Net::Twitter: 3
  Try::Tiny: 0
  WWW::Shorten: 3.02
  WWW::Shorten::Simple: 0
  WWW::Shorten::TinyURL: 0
  namespace::autoclean: 0.09
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-Plugin-Twitter/issues
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-Twitter/
  repository: git://github.com/doherty/Dist-Zilla-Plugin-Twitter.git
version: 0.020
